const KEY='rs_chatrabash_final_2';const MONTHS=['জানুয়ারি','ফেব্রুয়ারি','মার্চ','এপ্রিল','মে','জুন','জুলাই','আগস্ট','সেপ্টেম্বর','অক্টোবর','নভেম্বর','ডিসেম্বর'];
const SEED=[["101", "ইয়াহিয়া", 1100], ["101", "জিন্নুর", 1100], ["102", "আরিফ", 1100], ["102", "হেলাল", 1100], ["103", "মেহেদী হাসান", 1100], ["103", "মোরসালিন", 1100], ["104", "বখতিয়ার", 1100], ["104", "আবু বক্কর সিদ্দিক", 1100], ["105", "মুরাদ", 1100], ["105", "সোহান রানা", 1100], ["106", "সিয়াম", 1100], ["106", "হাস্নাত", 1100], ["107", "লাভলু", 1100], ["107", "মেহেদি", 1100], ["108", "নাাজিম", 1100], ["108", "মজিবুল", 1100], ["109", "সোহাগ", 1100], ["109", "রিয়াদ", 1100], ["110", "রাশেদ", 0], ["111", "সাগর", 1260], ["111", "মজনু", 1260], ["112", "সুজন", 1160], ["112", "জিহাদ", 1160], ["113", "শাহরিয়ার", 1160], ["113", "তাকাব্বির", 1160], ["114", "মুন্না", 1160], ["114", "মমিন", 1160], ["115", "সোহেল", 1160], ["115", "সজীব বাবু", 1160], ["116", "প্রান্ত", 1160], ["116", "লিমন", 1160], ["117", "আরিফ", 1160], ["117", "রিফাত", 1160], ["118", "জাহিদ", 1230], ["119", "আবু সাইদ", 1230], ["120", "অর্ণব", 1230], ["121", "রবিউল", 1230]];
let db=load();
function n(x){return Number(String(x??'').replace(/,/g,''))||0}function money(x){return '৳'+n(x).toLocaleString('en-US')}function esc(x){return String(x??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m])}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x&&x.members)return x}catch(e){}return {mess:{name:'RS Chatrabash',location:'পার্কমোড়, রংপুর',address:'',monitor:'',phone:''},wifiDefault:0,members:SEED.map((s,i)=>({id:String(i+1),room:s[0],name:s[1],rent:s[2],deposit:0,depositAdjusted:0,depositRefund:0,phone:'',address:'',district:'',upazila:'',joining:'',leaving:'',status:'active',rentPayments:{},wifiPayments:{},wifiFee:0}))}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}function active(){return db.members.filter(m=>m.status==='active')}function current(m,i){let due=0,adv=0;for(let k=0;k<=i;k++){let paid=n((m.rentPayments[k]||[]).reduce((a,p)=>a+n(p.amount),0));let b=n(m.rent)+due-adv-paid;due=Math.max(b,0);adv=Math.max(-b,0)}return {due,adv}}
function rstate(m,i){let p=i?current(m,i-1):{due:0,adv:0};let paid=n((m.rentPayments[i]||[]).reduce((a,p)=>a+n(p.amount),0));let total=Math.max(n(m.rent)+p.due-p.adv,0),b=total-paid;return {rent:n(m.rent),paid,prevDue:p.due,prevAdv:p.adv,total,due:Math.max(b,0),adv:Math.max(-b,0),collection:i===11?'জানুয়ারি ২০২৭':MONTHS[i+1]+' ২০২৬'}}
function wstate(m,i){let due=0,adv=0;for(let k=0;k<=i;k++){let fee=n(m.wifiFee||db.wifiDefault),paid=n((m.wifiPayments[k]||[]).reduce((a,p)=>a+n(p.amount),0)),b=fee+due-adv-paid;due=Math.max(b,0);adv=Math.max(-b,0)}let p=i? wstate(m,i-1):{due:0,adv:0};let fee=n(m.wifiFee||db.wifiDefault),paid=n((m.wifiPayments[i]||[]).reduce((a,p)=>a+n(p.amount),0)),b=fee+p.due-p.adv-paid;return {fee,paid,prevDue:p.due,prevAdv:p.adv,due:Math.max(b,0),adv:Math.max(-b,0)}}
function go(v){location.hash=v;render()}window.addEventListener('hashchange',render);document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));
function render(){renderDash();renderBorders();renderRent();renderWifi();renderReports();renderSettings();let h=location.hash.slice(1)||'dashboard';document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===h));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===h))}
function renderDash(){let a=active(),monthly=a.reduce((s,m)=>s+n(m.rent),0),due=a.reduce((s,m)=>s+current(m,11).due,0),adv=a.reduce((s,m)=>s+current(m,11).adv,0),dep=a.reduce((s,m)=>s+n(m.deposit),0),wd=a.reduce((s,m)=>s+wstate(m,11).due,0);dashboard.innerHTML=`<h2>ড্যাশবোর্ড</h2><div class="grid"><div class="card stat"><b>${a.length}</b><span class="muted">সক্রিয় বর্ডার</span></div><div class="card stat"><b>${money(monthly)}</b><span class="muted">মাসিক রুম ভাড়া</span></div><div class="card stat"><b>${money(due)}</b><span class="muted">রুম ভাড়া Due</span></div><div class="card stat"><b>${money(adv)}</b><span class="muted">রুম ভাড়া Advance</span></div><div class="card stat"><b>${money(dep)}</b><span class="muted">জামানত</span></div><div class="card stat"><b>${money(wd)}</b><span class="muted">WiFi Due</span></div></div><div class="card"><b>বর্তমান আদায়ের নিয়ম</b><p class="muted">প্রতি মাসের ভাড়া পরের মাসে আদায় হবে। সেপ্টেম্বর ২০২৬-এ আগস্টের ভাড়া আদায় হবে এবং জুলাইয়ের বকেয়া আগস্টের পাওনার সঙ্গে থাকবে। ডিসেম্বর ২০২৬-এর ভাড়া জানুয়ারি ২০২৭-এ আদায় হবে।</p></div>`}
function renderBorders(){borders.innerHTML=`<h2>বর্ডার</h2><div class="toolbar"><input id="bs" class="search" placeholder="নাম, রুম বা মোবাইল" oninput="borderList()"><button class="btn" onclick="memberModal()">নতুন বর্ডার</button></div><div id="bl"></div>`;borderList()}
function borderList(){let q=(document.getElementById('bs')?.value||'').toLowerCase(),a=db.members.filter(m=>`${m.name} ${m.room} ${m.phone}`.toLowerCase().includes(q));bl.innerHTML=a.map(m=>{let x=current(m,11);return `<div class="card"><div onclick="profile('${m.id}')"><div class="name">${esc(m.name)}</div><div class="muted">রুম ${m.room} · ভাড়া ${money(m.rent)} · ${m.status==='active'?'সক্রিয়':'সিট ছেড়েছে'}</div></div><div class="toolbar" style="margin-top:8px"><button class="btn" onclick="profile('${m.id}')">প্রোফাইল</button>${m.status==='active'?`<button class="btn btn2" onclick="memberModal('${m.id}')">সম্পাদনা</button><button class="btn danger" onclick="leftMember('${m.id}')">সিট ছেড়েছে</button>`:''}<span class="badge ${x.due?'due':x.adv?'adv':'paid'}">${x.due?'Due '+money(x.due):x.adv?'+ '+money(x.adv):'ঠিক আছে'}</span></div></div>`}).join('')||'<div class="card">কোনো সদস্য নেই</div>'}
function renderRent(){rent.innerHTML=`<h2>রুম ভাড়া</h2><div class="card"><select id="ri" onchange="rentList()">${MONTHS.map((m,i)=>`<option value="${i}" ${i===8?'selected':''}>আদায়: ${i===11?'জানুয়ারি ২০২৭':MONTHS[i+1]+' ২০২৬'} · ভাড়া: ${m} ২০২৬</option>`).join('')}</select><p class="muted">শুরুতে Opening Due = ৳0। আগের Due/Advance নিজে থেকে carry হবে।</p></div><div id="rl"></div>`;rentList()}
function rentList(){let i=n(ri.value);rl.innerHTML=active().map(m=>{let x=rstate(m,i);return `<div class="card"><div class="name">${esc(m.name)}</div><div class="muted">রুম ${m.room} · ভাড়া ${money(x.rent)} · আদায় ${x.collection}</div><p class="muted">আগের Due ${money(x.prevDue)} · আগের + ${money(x.prevAdv)} · মোট পাওনা ${money(x.total)} · জমা ${money(x.paid)}</p><span class="badge ${x.due?'due':x.adv?'adv':'paid'}">${x.due?'Due '+money(x.due):x.adv?'+ '+money(x.adv):'পরিশোধ সম্পন্ন'}</span> <button class="btn" onclick="payModal('${m.id}',${i})">Payment</button></div>`}).join('')}
function payModal(id,i){let m=db.members.find(x=>x.id===id),x=rstate(m,i);modal(`<h2>${esc(m.name)} · ${MONTHS[i]} ২০২৬</h2><div class="card">আদায় মাস: <b>${x.collection}</b><br>আগের Due: <b>${money(x.prevDue)}</b><br>আগের Advance: <b>${money(x.prevAdv)}</b><br>মোট পাওনা: <b>${money(x.total)}</b><br>এখন পর্যন্ত জমা: <b>${money(x.paid)}</b><br>বর্তমান Due: <b>${money(x.due)}</b> · Advance: <b>${money(x.adv)}</b></div><div class="field"><label>আজ কত টাকা দিল?</label><input id="amt" type="number" min="0"></div><div class="field"><label>তারিখ</label><input id="pdate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="actions"><button class="btn btn2" onclick="closeM()">বাতিল</button><button class="btn" onclick="savePay('${id}',${i})">সংরক্ষণ</button></div>`)}
function savePay(id,i){let a=n(amt.value);if(a<=0){alert('টাকার পরিমাণ দিন');return}let m=db.members.find(x=>x.id===id);m.rentPayments[i]=m.rentPayments[i]||[];m.rentPayments[i].push({amount:a,date:pdate.value});save();closeM();render()}
function renderWifi(){wifi.innerHTML=`<h2>WiFi Connection Fee</h2><div class="card"><b>সম্পূর্ণ আলাদা হিসাব</b><p class="muted">WiFi-এর Payment, Due ও Advance Room Rent-এর সঙ্গে merge হবে না।</p><div class="field"><label>ডিফল্ট মাসিক WiFi Fee</label><input type="number" value="${n(db.wifiDefault)}" onchange="db.wifiDefault=n(this.value);save();renderWifi()"></div></div><div id="wm"></div>`;wm.innerHTML=active().map(m=>{let x=wstate(m,8);return `<div class="card"><div class="name">${esc(m.name)}</div><div class="muted">রুম ${m.room} · WiFi Fee ${money(x.fee)}</div><p class="muted">আগের Due ${money(x.prevDue)} · আগের + ${money(x.prevAdv)} · জমা ${money(x.paid)}</p><span class="badge ${x.due?'due':x.adv?'adv':'paid'}">${x.due?'Due '+money(x.due):x.adv?'+ '+money(x.adv):'ঠিক আছে'}</span> <button class="btn" onclick="wifiPay('${m.id}',8)">Payment</button></div>`}).join('')}
function wifiPay(id,i){let m=db.members.find(x=>x.id===id),x=wstate(m,i);modal(`<h2>${esc(m.name)} · WiFi</h2><div class="card">Fee ${money(x.fee)}<br>আগের Due ${money(x.prevDue)}<br>আগের Advance ${money(x.prevAdv)}<br>জমা ${money(x.paid)}<br>Due ${money(x.due)} · Advance ${money(x.adv)}</div><div class="field"><label>Payment</label><input id="amt" type="number" min="0"></div><div class="field"><label>তারিখ</label><input id="pdate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="actions"><button class="btn btn2" onclick="closeM()">বাতিল</button><button class="btn" onclick="saveWifi('${id}',${i})">সংরক্ষণ</button></div>`)}
function saveWifi(id,i){let a=n(amt.value);if(a<=0){alert('টাকার পরিমাণ দিন');return}let m=db.members.find(x=>x.id===id);m.wifiPayments[i]=m.wifiPayments[i]||[];m.wifiPayments[i].push({amount:a,date:pdate.value});save();closeM();render()}
function profile(id){let m=db.members.find(x=>x.id===id),r=current(m,11),w=wstate(m,11);modal(`<h2>${esc(m.name)}</h2><div class="card">রুম ${m.room}<br>মাসিক ভাড়া ${money(m.rent)}<br>মোবাইল ${esc(m.phone||'নেই')}<br>জামানত ${money(m.deposit)}<br>রুম Due ${money(r.due)} · Advance ${money(r.adv)}<br>WiFi Due ${money(w.due)} · Advance ${money(w.adv)}</div><h3>জামানত</h3><div class="card">সমন্বয় ${money(m.depositAdjusted)} · ফেরত ${money(m.depositRefund)} · অবশিষ্ট ${money(Math.max(n(m.deposit)-n(m.depositAdjusted)-n(m.depositRefund),0))}</div><button class="btn" onclick="depositModal('${id}')">জামানত থেকে Rent Due সমন্বয়</button><h3>২০২৬ রুম ভাড়ার পূর্ণ ইতিহাস</h3><div class="card"><table><tr><th>ভাড়া মাস</th><th>আদায়</th><th>আগের Due</th><th>জমা</th><th>Due</th><th>+</th></tr>${MONTHS.map((mo,i)=>{let x=rstate(m,i);return `<tr><td>${mo}</td><td>${x.collection}</td><td>${money(x.prevDue)}</td><td>${money(x.paid)}</td><td>${money(x.due)}</td><td>${money(x.adv)}</td></tr>`}).join('')}</table></div><h3>WiFi ইতিহাস</h3><div class="card"><table><tr><th>মাস</th><th>Fee</th><th>জমা</th><th>Due</th><th>+</th></tr>${MONTHS.map((mo,i)=>{let x=wstate(m,i);return `<tr><td>${mo}</td><td>${money(x.fee)}</td><td>${money(x.paid)}</td><td>${money(x.due)}</td><td>${money(x.adv)}</td></tr>`}).join('')}</table></div>`)}
function depositModal(id){
let m=db.members.find(x=>x.id===id);
let rem=Math.max(n(m.deposit)-n(m.depositAdjusted)-n(m.depositRefund),0);
let due=current(m,11).due;
modal(`<h2>${esc(m.name)} · জামানত নিষ্পত্তি</h2>
<div class="card">
জামানত: <b>${money(m.deposit)}</b><br>
আগে সমন্বয়: <b>${money(m.depositAdjusted)}</b><br>
আগে ফেরত: <b>${money(m.depositRefund)}</b><br>
অবশিষ্ট জামানত: <b>${money(rem)}</b><br>
বর্তমান Rent Due: <b>${money(due)}</b>
</div>
<div class="field"><label>জামানত থেকে Rent Due-তে সমন্বয়</label><input id="adj" type="number" min="0" max="${Math.min(rem,due)}" placeholder="সর্বোচ্চ ${money(Math.min(rem,due))}"></div>
<div class="field"><label>বর্ডারকে ফেরত দেওয়া জামানত</label><input id="ref" type="number" min="0" max="${rem}" placeholder="ফেরত টাকা"></div>
<p class="muted">সিট ছাড়ার সময় আগে Rent Due সমন্বয় হবে। জামানত বাকি থাকলে সেটি ফেরত দেওয়ার টাকা হিসেবে রাখা যাবে।</p>
<div class="actions"><button class="btn btn2" onclick="closeM()">বাতিল</button><button class="btn" onclick="saveDep('${id}')">সংরক্ষণ</button></div>`)}
function memberModal(id){let m=id?db.members.find(x=>x.id===id):{name:'',room:'',rent:0,deposit:0,phone:'',address:'',district:'',upazila:'',joining:'',wifiFee:0,status:'active',rentPayments:{},wifiPayments:{}};modal(`<h2>${id?'বর্ডার সম্পাদনা':'নতুন বর্ডার'}</h2><div class="two"><div class="field"><label>নাম</label><input id="fn" value="${esc(m.name)}"></div><div class="field"><label>রুম</label><input id="fr" value="${esc(m.room)}"></div><div class="field"><label>মাসিক রুম ভাড়া</label><input id="frr" type="number" value="${n(m.rent)}"></div><div class="field"><label>জামানত</label><input id="fd" type="number" value="${n(m.deposit)}"></div><div class="field"><label>মোবাইল</label><input id="fp" value="${esc(m.phone)}"></div><div class="field"><label>মেসে ওঠার তারিখ</label><input id="fj" type="date" value="${esc(m.joining)}"></div><div class="field"><label>উপজেলা</label><input id="fu" value="${esc(m.upazila)}"></div><div class="field"><label>জেলা</label><input id="fdi" value="${esc(m.district)}"></div></div><div class="field"><label>ঠিকানা</label><textarea id="fa">${esc(m.address)}</textarea></div><div class="field"><label>ব্যক্তিগত WiFi Fee (০ হলে ডিফল্ট)</label><input id="fw" type="number" value="${n(m.wifiFee)}"></div><div class="actions"><button class="btn btn2" onclick="closeM()">বাতিল</button><button class="btn" onclick="saveMember('${id||''}')">সংরক্ষণ</button></div>`)}
function saveMember(id){let m=id?db.members.find(x=>x.id===id):null;if(!m){m={id:String(Date.now()),status:'active',rentPayments:{},wifiPayments:{},depositAdjusted:0,depositRefund:0};db.members.push(m)}m.name=fn.value.trim();m.room=fr.value.trim();m.rent=n(frr.value);m.deposit=n(fd.value);m.phone=fp.value.trim();m.joining=fj.value;m.upazila=fu.value.trim();m.district=fdi.value.trim();m.address=fa.value.trim();m.wifiFee=n(fw.value);save();closeM();render()}
function leftMember(id){let m=db.members.find(x=>x.id===id);if(confirm(m.name+'-কে সিট ছেড়েছে হিসেবে চিহ্নিত করবেন?')){m.status='left';m.leaving=new Date().toISOString().slice(0,10);save();render()}}
function renderReports(){reports.innerHTML=`<h2>রিপোর্ট</h2><div class="card">Active ${active().length}<br>মাসিক Rent ${money(active().reduce((s,m)=>s+n(m.rent),0))}<br>Rent Due ${money(active().reduce((s,m)=>s+current(m,11).due,0))}<br>Rent Advance ${money(active().reduce((s,m)=>s+current(m,11).adv,0))}<br>WiFi Due ${money(active().reduce((s,m)=>s+wstate(m,11).due,0))}</div><button class="btn" onclick="backup()">Backup</button>`}
function renderSettings(){settings.innerHTML=`<h2>সেটিংস</h2><div class="card"><b>${esc(db.mess.name)}</b><p class="muted">${esc(db.mess.location)}</p></div><div class="card"><button class="btn" onclick="backup()">Backup Download</button> <label class="btn btn2">Restore<input type="file" accept="application/json" hidden onchange="restore(event)"></label></div><button class="btn danger" onclick="resetData()">সব ডাটা মুছুন</button>`}
function backup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='RS_Chatrabash_Backup.json';a.click()}
function restore(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.members)throw 0;db=x;save();render();alert('Restore সফল')}catch{alert('ভুল Backup')}};r.readAsText(f)}
function resetData(){if(confirm('সব ডাটা মুছে ৩৭ জনের ডিফল্ট তালিকায় ফিরবেন?')){localStorage.removeItem(KEY);db=load();render()}}
function modal(h){sheet.innerHTML=h;document.getElementById('modal').classList.add('open')}function closeM(){document.getElementById('modal').classList.remove('open')}document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeM()};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}));
render();
